chore: sync template files (#178)
Co-authored-by: github-actions[bot] <41898282+github-actions[bot]@users.noreply.github.com>

diff --git a/taskfiles/build.yml b/taskfiles/build.yml
--- a/taskfiles/build.yml
+++ b/taskfiles/build.yml
@@ -1,12 +1,20 @@
 version: '3'
 
+dir: .
+
 tasks:
   uv:
     desc: Install uv and uvx
     cmds:
       - |
+        echo "PWD: $PWD"
         # install uv and uvx
-        curl -sSf https://astral.sh/uv/install.sh | sh > /dev/null 2>&1 || { echo "${RED}Installation failed!${RESET}" >&2; exit 1; }
+        if [ -f "./bin/uv" ] && [ -x "./bin/uv" ]; then
+          printf "{{.BLUE}}[INFO] uv already present in ./bin, skipping installation{{.RESET}}\n"
+        else
+          printf "{{.BLUE}}Installing uv{{.RESET}}\n"
+          curl -LsSf https://astral.sh/uv/install.sh | UV_INSTALL_DIR="./bin" sh || { printf "{{.RED}}[ERROR] Failed to install uv{{.RESET}}\n"; exit 1; }
+        fi
 
   install:
     desc: Install all dependencies using uv
@@ -19,16 +27,16 @@ tasks:
         else
           # we need the virtual environment at least for the tests to work
           # even if we don't install anything
-          
+
           # Create the virtual environment
           printf "${BLUE}[INFO] Creating virtual environment...${RESET}\n"
-          
+
           # Create the virtual environment
-          uv venv --python 3.12 || { printf "${RED}[ERROR] Failed to create virtual environment${RESET}\n"; exit 1; }
-          
+          ./bin/uv venv --python 3.12 || { printf "${RED}[ERROR] Failed to create virtual environment${RESET}\n"; exit 1; }
+
           if [ -f "pyproject.toml" ]; then
             printf "${BLUE}[INFO] Installing dependencies${RESET}\n"
-            uv sync --all-extras --frozen || { printf "${RED}[ERROR] Failed to install dependencies${RESET}\n"; exit 1; }
+            ./bin/uv sync --all-extras --frozen || { printf "${RED}[ERROR] Failed to install dependencies${RESET}\n"; exit 1; }
           else
             printf "${YELLOW}[WARN] No pyproject.toml found, skipping install${RESET}\n"
           fi
@@ -40,7 +48,9 @@ tasks:
     cmds:
       - |
         if [ -f "pyproject.toml" ]; then
-          uvx hatch build || { printf "${RED}[ERROR] Build failed${RESET}\n"; exit 1; }
+          printf "${BLUE}[INFO] Building package...${RESET}\n"
+          ./bin/uv pip install hatch
+          ./bin/uv run hatch build
         else
           printf "${YELLOW}[WARN] No pyproject.toml found, skipping build${RESET}\n"
         fi
